:PROPERTIES:
:ID:       fa631099-7451-4086-beb8-3d67a35a9ac5
:END:
#+title: footprinting
#+OPTIONS: toc:2

* TOC :toc:
- [[#enumeration][Enumeration]]
  - [[#methodology][Methodology]]
- [[#infra-based][Infra Based]]
  - [[#domain-info][Domain info]]
  - [[#cloud-resources][Cloud Resources]]
- [[#host-based][Host Based]]
  - [[#ftp][FTP]]
  - [[#tftp][TFTP]]

* Enumeration
** Methodology
- divided into:
  1. [[*Infra Based][Infra Based]]
  2. Host Based Enumeration
  3. OS-based Enumeration
*** Layers
1. Internet Presence
2. Gateway
3. Accessible Servers
4. Processes
5. Privileges
4. OS Setup
* Infra Based
** Domain info
- gathered w/out direct & active scans.
- remain hidden

1. first point of presence -> =SSL Cert= from company's main website.
   - may include more than subdomain.
   - means cert used for several domains.
   - most likely still active.
2. [[https://crt.sh/][Certificate Transparency logs]]
   - RFFC 6962 -> logging of all difital Certificates issued by a certificate auth in audit-proof logs.
   - detection of false Certificates for domain.
     
***** filter by subdomain
   ~curl -s https://crt.sh/\?q\=inlanefreight.com\&output\=json | jq . | grep name | cut -d":" -f2 | grep -v "CN=" | cut -d'"' -f2 | awk '{gsub(/\\n/,"\n");}1;' | sort -u~

***** company hosted server
~for i in $(cat subdomainlist);do host $i | grep "has address" | grep inlanefreight.com | cut -d" " -f1,4;done~

*** Shodan
- find devices and systems permanently connected to the Internet (IoT)
- searches internet for open TCP/IP ports, filters systems according to specific terms & conds
- open HTTP/S, FTP, SSH, SNMP, Telnet, RTSP, SIP searched
- can find surveillance cams, servers, smart home, industrial controllers, traffic lights, traffic controllers.

**** IP list 
  #+begin_src bash
biscuitrescue@htb[/htb]$ for i in $(cat subdomainlist);do host $i | grep "has address" | grep inlanefreight.com | cut -d" " -f4 >> ip-addresses.txt;done
biscuitrescue@htb[/htb]$ for i in $(cat ip-addresses.txt);do shodan host $i;done

10.129.24.93
City:                    Berlin
Country:                 Germany
Organization:            InlaneFreight
Updated:                 2021-09-01T09:02:11.370085
Number of open ports:    2

Ports:
     80/tcp nginx 
    443/tcp nginx 
    
10.129.27.33
City:                    Berlin
Country:                 Germany
Organization:            InlaneFreight
Updated:                 2021-08-30T22:25:31.572717
Number of open ports:    3

Ports:
     22/tcp OpenSSH (7.6p1 Ubuntu-4ubuntu0.3)
     80/tcp nginx 
    443/tcp nginx 
        |-- SSL Versions: -SSLv2, -SSLv3, -TLSv1, -TLSv1.1, -TLSv1.3, TLSv1.2
        |-- Diffie-Hellman Parameters:
                Bits:          2048
                Generator:     2
                
10.129.27.22
City:                    Berlin
Country:                 Germany
Organization:            InlaneFreight
Updated:                 2021-09-01T15:39:55.446281
Number of open ports:    8

Ports:
     25/tcp  
        |-- SSL Versions: -SSLv2, -SSLv3, -TLSv1, -TLSv1.1, TLSv1.2, TLSv1.3
     53/tcp  
     53/udp  
     80/tcp Apache httpd 
     81/tcp Apache httpd 
    110/tcp  
        |-- SSL Versions: -SSLv2, -SSLv3, -TLSv1, -TLSv1.1, TLSv1.2
    111/tcp  
    443/tcp Apache httpd 
        |-- SSL Versions: -SSLv2, -SSLv3, -TLSv1, -TLSv1.1, TLSv1.2, TLSv1.3
        |-- Diffie-Hellman Parameters:
                Bits:          2048
                Generator:     2
                Fingerprint:   RFC3526/Oakley Group 14
    444/tcp  
        
10.129.27.33
City:                    Berlin
Country:                 Germany
Organization:            InlaneFreight
Updated:                 2021-08-30T22:25:31.572717
Number of open ports:    3

Ports:
     22/tcp OpenSSH (7.6p1 Ubuntu-4ubuntu0.3)
     80/tcp nginx 
    443/tcp nginx 
        |-- SSL Versions: -SSLv2, -SSLv3, -TLSv1, -TLSv1.1, -TLSv1.3, TLSv1.2
        |-- Diffie-Hellman Parameters:
                Bits:          2048
                Generator:     2
  #+end_src

*** DNS Records
~dig any inlanefrieght.com~

1. =A= records:
   - Ip addr which point to specific location through the A Records
   - only see one we already know

2. =MX= records:
   - Mail server records.
   - show which mail server is respoinsible for managing emails for company.
     
3. =NS= records:
   - which name servers used to resolve FQDN to IP addr. Most providers use their own name.
     
4. =txt= Records:
   - contain verification keys for diff third-party providers and other security aspects of DNS -> SPF, DMARC, DKIM.

     #+begin_src bash
...SNIP... TXT     "MS=ms92346782372"
...SNIP... TXT     "atlassian-domain-verification=IJdXMt1rKCy68JFszSdCKVpwPN"
...SNIP... TXT     "google-site-verification=O7zV5-xFh_jn7JQ31"
...SNIP... TXT     "google-site-verification=bow47-er9LdgoUeah"
...SNIP... TXT     "google-site-verification=gZsCG-BINLopf4hr2"
...SNIP... TXT     "logmein-verification-code=87123gff5a479e-61d4325gddkbvc1-b2bnfghfsed1-3c789427sdjirew63fc"
...SNIP... TXT     "v=spf1 include:mailgun.org include:_spf.google.com include:spf.protection.outlook.com include:_spf.atlassian.net ip4:10.129.24.8 ip4:10.129.27.2 ip4:10.72.82.106 ~all"
     #+end_src

** Cloud Resources 
- google dorks =inurl:=, =intext:=
- [[https://domain.glass/][domain,glass]]
- [[https://buckets.grayhatwarfare.com/][Grayhatwarfare]]
  
* Host Based
** FTP
- one of the oldest protocols.
- runs on application layer of TCP/IP stack.
- =Clear Text= protocol
  
*** Upload / Download
1. 2 channels opened
2. client/server est connection -> =TCP 21=.
3. client sends commands to server. server ret status codes.
4. both comm participants can est data channel -> =TCP 20=. =20= exclusively for data transmission.
5. protocol watches for errs.
6. if connection broken during transmission, transport resumed after re-est contact.

*** Active FTP
- client est connection via =TCP 20=.
- informs server which client-side port server can transmit its responses to.
- if firewall protects client, server can't reply -> all external connections blocked.
  
*** Passive FTP
- server announces port through which client can est data channel
- firewall doesnt block transfer as client init connection.

*** Commands & Status codes
- [[https://web.archive.org/web/20230326204635/https://www.smartfile.com/blog/the-ultimate-ftp-commands-list/][commands]]
- [[https://en.wikipedia.org/wiki/List_of_FTP_server_return_codes][status codes]]

** TFTP
