:PROPERTIES:
:ID:       fa631099-7451-4086-beb8-3d67a35a9ac5
:END:
#+title: footprinting
#+OPTIONS: toc:2

* TOC :toc:
- [[#enumeration][Enumeration]]
  - [[#methodology][Methodology]]
- [[#infra-based][Infra Based]]
  - [[#domain-info][Domain info]]
  - [[#cloud-resources][Cloud Resources]]
- [[#host-based][Host Based]]
  - [[#ftp][FTP]]
  - [[#tftp][TFTP]]
  - [[#footprinting-service][footprinting service]]
  - [[#smb][SMB]]

* Enumeration
** Methodology
- divided into:
  1. [[*Infra Based][Infra Based]]
  2. Host Based Enumeration
  3. OS-based Enumeration
*** Layers
1. Internet Presence
2. Gateway
3. Accessible Servers
4. Processes
5. Privileges
4. OS Setup
* Infra Based
** Domain info
- gathered w/out direct & active scans.
- remain hidden

1. first point of presence -> =SSL Cert= from company's main website.
   - may include more than subdomain.
   - means cert used for several domains.
   - most likely still active.
2. [[https://crt.sh/][Certificate Transparency logs]]
   - RFFC 6962 -> logging of all difital Certificates issued by a certificate auth in audit-proof logs.
   - detection of false Certificates for domain.
     
***** filter by subdomain
   ~curl -s https://crt.sh/\?q\=inlanefreight.com\&output\=json | jq . | grep name | cut -d":" -f2 | grep -v "CN=" | cut -d'"' -f2 | awk '{gsub(/\\n/,"\n");}1;' | sort -u~

***** company hosted server
~for i in $(cat subdomainlist);do host $i | grep "has address" | grep inlanefreight.com | cut -d" " -f1,4;done~

*** Shodan
- find devices and systems permanently connected to the Internet (IoT)
- searches internet for open TCP/IP ports, filters systems according to specific terms & conds
- open HTTP/S, FTP, SSH, SNMP, Telnet, RTSP, SIP searched
- can find surveillance cams, servers, smart home, industrial controllers, traffic lights, traffic controllers.

**** IP list 
  #+begin_src bash
biscuitrescue@htb[/htb]$ for i in $(cat subdomainlist);do host $i | grep "has address" | grep inlanefreight.com | cut -d" " -f4 >> ip-addresses.txt;done
biscuitrescue@htb[/htb]$ for i in $(cat ip-addresses.txt);do shodan host $i;done

10.129.24.93
City:                    Berlin
Country:                 Germany
Organization:            InlaneFreight
Updated:                 2021-09-01T09:02:11.370085
Number of open ports:    2

Ports:
     80/tcp nginx 
    443/tcp nginx 
    
10.129.27.33
City:                    Berlin
Country:                 Germany
Organization:            InlaneFreight
Updated:                 2021-08-30T22:25:31.572717
Number of open ports:    3

Ports:
     22/tcp OpenSSH (7.6p1 Ubuntu-4ubuntu0.3)
     80/tcp nginx 
    443/tcp nginx 
        |-- SSL Versions: -SSLv2, -SSLv3, -TLSv1, -TLSv1.1, -TLSv1.3, TLSv1.2
        |-- Diffie-Hellman Parameters:
                Bits:          2048
                Generator:     2
                
10.129.27.22
City:                    Berlin
Country:                 Germany
Organization:            InlaneFreight
Updated:                 2021-09-01T15:39:55.446281
Number of open ports:    8

Ports:
     25/tcp  
        |-- SSL Versions: -SSLv2, -SSLv3, -TLSv1, -TLSv1.1, TLSv1.2, TLSv1.3
     53/tcp  
     53/udp  
     80/tcp Apache httpd 
     81/tcp Apache httpd 
    110/tcp  
        |-- SSL Versions: -SSLv2, -SSLv3, -TLSv1, -TLSv1.1, TLSv1.2
    111/tcp  
    443/tcp Apache httpd 
        |-- SSL Versions: -SSLv2, -SSLv3, -TLSv1, -TLSv1.1, TLSv1.2, TLSv1.3
        |-- Diffie-Hellman Parameters:
                Bits:          2048
                Generator:     2
                Fingerprint:   RFC3526/Oakley Group 14
    444/tcp  
        
10.129.27.33
City:                    Berlin
Country:                 Germany
Organization:            InlaneFreight
Updated:                 2021-08-30T22:25:31.572717
Number of open ports:    3

Ports:
     22/tcp OpenSSH (7.6p1 Ubuntu-4ubuntu0.3)
     80/tcp nginx 
    443/tcp nginx 
        |-- SSL Versions: -SSLv2, -SSLv3, -TLSv1, -TLSv1.1, -TLSv1.3, TLSv1.2
        |-- Diffie-Hellman Parameters:
                Bits:          2048
                Generator:     2
  #+end_src

*** DNS Records
~dig any inlanefrieght.com~

1. =A= records:
   - Ip addr which point to specific location through the A Records
   - only see one we already know

2. =MX= records:
   - Mail server records.
   - show which mail server is respoinsible for managing emails for company.
     
3. =NS= records:
   - which name servers used to resolve FQDN to IP addr. Most providers use their own name.
     
4. =txt= Records:
   - contain verification keys for diff third-party providers and other security aspects of DNS -> SPF, DMARC, DKIM.

     #+begin_src bash
...SNIP... TXT     "MS=ms92346782372"
...SNIP... TXT     "atlassian-domain-verification=IJdXMt1rKCy68JFszSdCKVpwPN"
...SNIP... TXT     "google-site-verification=O7zV5-xFh_jn7JQ31"
...SNIP... TXT     "google-site-verification=bow47-er9LdgoUeah"
...SNIP... TXT     "google-site-verification=gZsCG-BINLopf4hr2"
...SNIP... TXT     "logmein-verification-code=87123gff5a479e-61d4325gddkbvc1-b2bnfghfsed1-3c789427sdjirew63fc"
...SNIP... TXT     "v=spf1 include:mailgun.org include:_spf.google.com include:spf.protection.outlook.com include:_spf.atlassian.net ip4:10.129.24.8 ip4:10.129.27.2 ip4:10.72.82.106 ~all"
     #+end_src

** Cloud Resources 
- google dorks =inurl:=, =intext:=
- [[https://domain.glass/][domain,glass]]
- [[https://buckets.grayhatwarfare.com/][Grayhatwarfare]]
  
* Host Based
** FTP
- one of the oldest protocols.
- runs on application layer of TCP/IP stack.
- =Clear Text= protocol
  
*** Upload / Download
1. 2 channels opened
2. client/server est connection -> =TCP 21=.
3. client sends commands to server. server ret status codes.
4. both comm participants can est data channel -> =TCP 20=. =20= exclusively for data transmission.
5. protocol watches for errs.
6. if connection broken during transmission, transport resumed after re-est contact.

*** Active FTP
- client est connection via =TCP 20=.
- informs server which client-side port server can transmit its responses to.
- if firewall protects client, server can't reply -> all external connections blocked.
  
*** Passive FTP
- server announces port through which client can est data channel
- firewall doesnt block transfer as client init connection.

*** Commands & Status codes
- [[https://web.archive.org/web/20230326204635/https://www.smartfile.com/blog/the-ultimate-ftp-commands-list/][commands]]
- [[https://en.wikipedia.org/wiki/List_of_FTP_server_return_codes][status codes]]

** TFTP
- simpler
- doesn't provide user auth.
- =UDP= -> unreliable, UDP assisted application recovery
- sets limit on access -> r/w permissions of file in OS
- leads to TFTP operating exclusively in dirs w files which have been shared w all users and can be read and written globally.

*** commands
1. connect: sets remote host, optional::port
2. get: transfer a file or set of files from remote host to local host
3. put: transfers file/set of files from localhost to remote
4. quit: exit tftp
5. status: show the current status of tftp, including current transfer mode (ascii/bin), connection status, time-out val, etc
6. verbose
   
*** Download all avl files
   #+begin_src bash
wget -m --no-passive ftp://anonymous:anonymous@<ip>
   #+end_src

** footprinting service

*** Nmap ftp scripts
~--script-updatedb~
~--script-trace~

*** Openssl
- if ftp server runs w TLS/SSL cert.
- SSL -> allows us to recognise =username= & =email_address=
  #+begin_src bash
openssl s_client -connect <ip> -starttls ftp
#+end_src

** SMB
- regulates access top files and entire dirs and other net Resources (printers, routers, interfaces)
- backward compatible
- uses =TCP= to establish connection. specs of TCP -> transport of data
- SMB server -> arbitrary parts of local FS as shares.
- hierarchy visible to client is partially independent of struct on server.
- access rights by =ACLs=

  
*** Samba
- alternate impl of SMB server for Unix based
- impls =CIFS= (dialect of SMB)
  - allows samba to comm effectively w newer windows systems
    
+ SMB cmds from samba to older NetBIOS system -> TCP (137, 138, 139)
+ CIFS -> TCP (445)

*** rpcclient
- nmap doesnt provide much for smb.
- allows to interact manually with SMB.
- performs MS-RPC functions.
  ~rpcclient -U "" <ip>~
  
**** commands
***** srvinfo
- server info
***** enumdomains
- enumerate all domains deployed in network
***** querydominfo
- provides domain, server and user info of deployed domains
***** netshareenumall
- enumerate all avl shares.
***** netsharegetinfo <share>
- provide info about specific share
***** enumdomusers
- enum all domain users.
***** queryuser <RID>
- Provide info about specific user

**** brute forcing user RIDs
***** bash script
  #+begin_src bash
biscuitrescue@htb[/htb]$ for i in $(seq 500 1100);do rpcclient -N -U "" 10.129.14.128 -c "queryuser 0x$(printf '%x\n' $i)" | grep "User Name\|user_rid\|group_rid" && echo "";done

        User Name   :   sambauser
        user_rid :      0x1f5
        group_rid:      0x201
        
        User Name   :   mrb3n
        user_rid :      0x3e8
        group_rid:      0x201
        
        User Name   :   cry0l1t3
        user_rid :      0x3e9
        group_rid:      0x201
  #+end_src
***** Impacket -> samrdump.py
- [[https://github.com/SecureAuthCorp/impacket/blob/master/examples/samrdump.py][url]]
- usage: ~samrdump.py <ip>~
**** alternatives
1. [[https://github.com/ShawnDEvans/smbmap][SMBMap]]
2. [[https://github.com/byt3bl33d3r/CrackMapExec][CrackMapExec]]
3. [[https://github.com/cddmp/enum4linux-ng][enum4linux-ng]]
*** SMBMap
#+begin_src bash
biscuitrescue@htb[/htb]$ smbmap -H 10.129.14.128

[+] Finding open SMB ports....
[+] User SMB session established on 10.129.14.128...
[+] IP: 10.129.14.128:445       Name: 10.129.14.128                                     
        Disk                                                    Permissions     Comment
        ----                                                    -----------     -------
        print$                                                  NO ACCESS       Printer Drivers
        home                                                    NO ACCESS       INFREIGHT Samba
        dev                                                     NO ACCESS       DEVenv
        notes                                                   NO ACCESS       CheckIT
        IPC$                                                    NO ACCESS       IPC Service (DEVSM)
#+end_src
*** CrackMapExec
#+begin_src bash
biscuitrescue@htb[/htb]$ crackmapexec smb 10.129.14.128 --shares -u '' -p ''

SMB         10.129.14.128   445    DEVSMB           [*] Windows 6.1 Build 0 (name:DEVSMB) (domain:) (signing:False) (SMBv1:False)
SMB         10.129.14.128   445    DEVSMB           [+] \: 
SMB         10.129.14.128   445    DEVSMB           [+] Enumerated shares
SMB         10.129.14.128   445    DEVSMB           Share           Permissions     Remark
SMB         10.129.14.128   445    DEVSMB           -----           -----------     ------
SMB         10.129.14.128   445    DEVSMB           print$                          Printer Drivers
SMB         10.129.14.128   445    DEVSMB           home                            INFREIGHT Samba
SMB         10.129.14.128   445    DEVSMB           dev                             DEVenv
SMB         10.129.14.128   445    DEVSMB           notes           READ,WRITE      CheckIT
SMB         10.129.14.128   445    DEVSMB           IPC$                            IPC Service (DEVSM)
#+end_src
*** Enum4linux-ng
#+begin_src bash
biscuitrescue@htb[/htb]$ ./enum4linux-ng.py 10.129.14.128 -A

ENUM4LINUX - next generation

 ==========================
|    Target Information    |
 ==========================
[*] Target ........... 10.129.14.128
[*] Username ......... ''
[*] Random Username .. 'juzgtcsu'
[*] Password ......... ''
[*] Timeout .......... 5 second(s)

 =====================================
|    Service Scan on 10.129.14.128    |
 =====================================
[*] Checking LDAP
[-] Could not connect to LDAP on 389/tcp: connection refused
[*] Checking LDAPS
[-] Could not connect to LDAPS on 636/tcp: connection refused
[*] Checking SMB
[+] SMB is accessible on 445/tcp
[*] Checking SMB over NetBIOS
[+] SMB over NetBIOS is accessible on 139/tcp

 =====================================================
|    NetBIOS Names and Workgroup for 10.129.14.128    |
 =====================================================
[+] Got domain/workgroup name: DEVOPS
[+] Full NetBIOS names information:
- DEVSMB          <00> -         H <ACTIVE>  Workstation Service
- DEVSMB          <03> -         H <ACTIVE>  Messenger Service
- DEVSMB          <20> -         H <ACTIVE>  File Server Service
- ..__MSBROWSE__. <01> - <GROUP> H <ACTIVE>  Master Browser
- DEVOPS          <00> - <GROUP> H <ACTIVE>  Domain/Workgroup Name
- DEVOPS          <1d> -         H <ACTIVE>  Master Browser
- DEVOPS          <1e> - <GROUP> H <ACTIVE>  Browser Service Elections
- MAC Address = 00-00-00-00-00-00

 ==========================================
|    SMB Dialect Check on 10.129.14.128    |
 ==========================================
[*] Trying on 445/tcp
[+] Supported dialects and settings:
SMB 1.0: false
SMB 2.02: true
SMB 2.1: true
SMB 3.0: true
SMB1 only: false
Preferred dialect: SMB 3.0
SMB signing required: false

 ==========================================
|    RPC Session Check on 10.129.14.128    |
 ==========================================
[*] Check for null session
[+] Server allows session using username '', password ''
[*] Check for random user session
[+] Server allows session using username 'juzgtcsu', password ''
[H] Rerunning enumeration with user 'juzgtcsu' might give more results

 ====================================================
|    Domain Information via RPC for 10.129.14.128    |
 ====================================================
[+] Domain: DEVOPS
[+] SID: NULL SID
[+] Host is part of a workgroup (not a domain)

 ============================================================
|    Domain Information via SMB session for 10.129.14.128    |
 ============================================================
[*] Enumerating via unauthenticated SMB session on 445/tcp
[+] Found domain information via SMB
NetBIOS computer name: DEVSMB
NetBIOS domain name: ''
DNS domain: ''
FQDN: htb

 ================================================
|    OS Information via RPC for 10.129.14.128    |
 ================================================
[*] Enumerating via unauthenticated SMB session on 445/tcp
[+] Found OS information via SMB
[*] Enumerating via 'srvinfo'
[+] Found OS information via 'srvinfo'
[+] After merging OS information we have the following result:
OS: Windows 7, Windows Server 2008 R2
OS version: '6.1'
OS release: ''
OS build: '0'
Native OS: not supported
Native LAN manager: not supported
Platform id: '500'
Server type: '0x809a03'
Server type string: Wk Sv PrQ Unx NT SNT DEVSM

 ======================================
|    Users via RPC on 10.129.14.128    |
 ======================================
[*] Enumerating users via 'querydispinfo'
[+] Found 2 users via 'querydispinfo'
[*] Enumerating users via 'enumdomusers'
[+] Found 2 users via 'enumdomusers'
[+] After merging user results we have 2 users total:
'1000':
  username: mrb3n
  name: ''
  acb: '0x00000010'
  description: ''
'1001':
  username: cry0l1t3
  name: cry0l1t3
  acb: '0x00000014'
  description: ''

 =======================================
|    Groups via RPC on 10.129.14.128    |
 =======================================
[*] Enumerating local groups
[+] Found 0 group(s) via 'enumalsgroups domain'
[*] Enumerating builtin groups
[+] Found 0 group(s) via 'enumalsgroups builtin'
[*] Enumerating domain groups
[+] Found 0 group(s) via 'enumdomgroups'

 =======================================
|    Shares via RPC on 10.129.14.128    |
 =======================================
[*] Enumerating shares
[+] Found 5 share(s):
IPC$:
  comment: IPC Service (DEVSM)
  type: IPC
dev:
  comment: DEVenv
  type: Disk
home:
  comment: INFREIGHT Samba
  type: Disk
notes:
  comment: CheckIT
  type: Disk
print$:
  comment: Printer Drivers
  type: Disk
[*] Testing share IPC$
[-] Could not check share: STATUS_OBJECT_NAME_NOT_FOUND
[*] Testing share dev
[-] Share doesn't exist
[*] Testing share home
[+] Mapping: OK, Listing: OK
[*] Testing share notes
[+] Mapping: OK, Listing: OK
[*] Testing share print$
[+] Mapping: DENIED, Listing: N/A

 ==========================================
|    Policies via RPC for 10.129.14.128    |
 ==========================================
[*] Trying port 445/tcp
[+] Found policy:
domain_password_information:
  pw_history_length: None
  min_pw_length: 5
  min_pw_age: none
  max_pw_age: 49710 days 6 hours 21 minutes
  pw_properties:
  - DOMAIN_PASSWORD_COMPLEX: false
  - DOMAIN_PASSWORD_NO_ANON_CHANGE: false
  - DOMAIN_PASSWORD_NO_CLEAR_CHANGE: false
  - DOMAIN_PASSWORD_LOCKOUT_ADMINS: false
  - DOMAIN_PASSWORD_PASSWORD_STORE_CLEARTEXT: false
  - DOMAIN_PASSWORD_REFUSE_PASSWORD_CHANGE: false
domain_lockout_information:
  lockout_observation_window: 30 minutes
  lockout_duration: 30 minutes
  lockout_threshold: None
domain_logoff_information:
  force_logoff_time: 49710 days 6 hours 21 minutes

 ==========================================
|    Printers via RPC for 10.129.14.128    |
 ==========================================
[+] No printers returned (this is not an error)

Completed after 0.61 seconds
#+end_src
